/**
 * Test data utilities for integration tests.
 * Provides functions to generate unique test identifiers and cleanup test data.
 */

import type { ApiClient } from "../../src/api/client.ts";

const TEST_PREFIX = "test-";

/**
 * Generate a unique workspace name for testing.
 */
export function generateWorkspaceName(): string {
  return `${TEST_PREFIX}workspace-${Date.now()}-${randomSuffix()}`;
}

/**
 * Check if a name was generated by test utilities.
 */
export function isTestResource(name: string): boolean {
  return name.startsWith(TEST_PREFIX);
}

/**
 * Cleanup all test workspaces created during testing.
 * Deletes workspaces whose names start with the test prefix.
 */
export async function cleanupTestWorkspaces(client: ApiClient): Promise<void> {
  const workspaces = await client.listAllWorkspaces();
  for (const workspace of workspaces) {
    if (workspace.name && isTestResource(workspace.name)) {
      try {
        await client.deleteWorkspace(workspace.id);
      } catch {
        // Ignore cleanup errors
      }
    }
  }
}

function randomSuffix(): string {
  return Math.random().toString(36).slice(2, 8);
}
