/**
 * Test data utilities for integration tests.
 * Provides functions to generate unique test identifiers and cleanup test data.
 */

import type { ApiClient } from "../../src/api/client.ts";

const TEST_PREFIX = "test-";

/**
 * Generate a unique project name for testing.
 */
export function generateProjectName(): string {
  return `${TEST_PREFIX}project-${Date.now()}-${randomSuffix()}`;
}

/**
 * Generate a unique task title for testing.
 */
export function generateTaskTitle(): string {
  return `${TEST_PREFIX}task-${Date.now()}-${randomSuffix()}`;
}

/**
 * Generate a unique repository name for testing.
 */
export function generateRepoName(): string {
  return `${TEST_PREFIX}repo-${Date.now()}-${randomSuffix()}`;
}

/**
 * Check if a name was generated by test utilities.
 */
export function isTestResource(name: string): boolean {
  return name.startsWith(TEST_PREFIX);
}

/**
 * Cleanup all test projects created during testing.
 * Deletes projects whose names start with the test prefix.
 */
export async function cleanupTestProjects(client: ApiClient): Promise<void> {
  const projects = await client.listProjects();
  for (const project of projects) {
    if (isTestResource(project.name)) {
      try {
        await client.deleteProject(project.id);
      } catch {
        // Ignore cleanup errors
      }
    }
  }
}

function randomSuffix(): string {
  return Math.random().toString(36).slice(2, 8);
}
